[tool.poetry]
name = "pair_mlops"
version = "0.1.0"
description = ""
authors = ["philippe.stepniewski <philippe.stepniewski@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.31.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

